- name: Configure webserver with nginx
  hosts: all
  become: True
  tasks:
    - name: install nginx
      apt: name=nginx update_cache=yes
    
    - name: copy nginx config file
      copy: src=files/default dest=/etc/nginx/sites-available/default
    
    - name: copiando nginx default
      copy: src=files/nginx.conf dest=/etc/nginx/nginx.conf
    
    - name: copiando nginx lb
      copy: src=files/load-balancer.conf dest=/etc/nginx/conf.d/load-balancer.conf
    
    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link
    
    - name: copy index.html
      template: src=files/index.html dest=/usr/share/nginx/html/index.html
        mode=0644
      
    - name: restart nginx
      service: name=nginx state=restarted