- hosts: masters
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: vagrant
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copies admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant

    - name: copiando arquivo com o manifesto
      copy:
        src: manifesto-calico.yaml
        dest: /tmp
        
    # está dando um erro estranho, parece que não reconhece o objeto, porém tem que rodar esse kubectl para funcionar
    - name: install Pod network
      become: yes
      become_user: vagrant
      shell: kubectl apply -f /tmp/manifesto-calico.yaml
      args:
        chdir: $HOME
        
    - name: Get the token for joining the worker nodes
      become: yes
      become_user: vagrant
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - name: debug
      debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      become: yes
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777