---
- hosts: gitlab-runners
  remote_user: vagrant
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
     - name: rodando scripts para instalar o kubectl awscli e gitlabrunner
       shell: |
              # instalando o kubectl
              apt-get install -y apt-transport-https ca-certificates curl
              curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
              echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
              apt-get update
              apt-get install -y kubectl
              mkdir /root/.kube
              touch /root/.kube/config

              ## instalando awscli
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install

              ## instalando gitlab runner (seguindo https://www.fosstechnix.com/how-to-install-gitlab-runner-on-ubuntu/)
              curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | sudo bash
              apt-get install gitlab-runner
              gitlab-runner -version
              gitlab-runner status
              echo 'gitlab-runner ALL=(ALL:ALL) ALL' >> /etc/sudoers
              echo 'gitlab-runner ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers